DB_USER = 'root'
DB_PASSWORD = 'acarepro2019'
DB_HOST = '119.3.150.173'
DB_DB = 'acarepro'
DB_PORT = 3306

DEBUG = True
PORT = 5000
HOST = "0.0.0.0"
SECRET_KEY = "my blog"

# SQLALCHEMY_TRACK_MODIFICATIONS = False
# SQLALCHEMY_DATABASE_URI = 'mysql://' + DB_USER + ':' + DB_PASSWORD + '@' + DB_HOST + '/' + DB_DB